conf
# renew_before_expiry = 30 days
version = 4.0.0
archive_dir = /etc/letsencrypt/archive/group04.hp.edu.technet.howest.be
cert = /etc/letsencrypt/live/group04.hp.edu.technet.howest.be/cert.pem
privkey = /etc/letsencrypt/live/group04.hp.edu.technet.howest.be/privkey.pem
chain = /etc/letsencrypt/live/group04.hp.edu.technet.howest.be/chain.pem
fullchain = /etc/letsencrypt/live/group04.hp.edu.technet.howest.be/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 2156c13c19c9a5c98399da2ac41b224f
server = https://ca.hp.edu.technet.howest.be/acme/acme/directory
authenticator = nginx
installer = nginx
key_type = ecdsa