; runs as www-data user/group, matching nginx's user, beneficial for them to talk to each other

; defines unix socket file for requests and owners and permissions of the file
[www]
user = www-data
group = www-data
listen = /run/php/php8.4-fpm.sock
listen.owner = www-data
listen.group = www-data
listen.mode = 0660

; process manager:
; mazimum 4 workers spawn when there is traffic/requests, kill them when they're idle forr 10 seconds.
; auto restart after 500 requests
pm = ondemand
pm.max_children = 4
pm.process_idle_timeout = 10s
pm.max_requests = 500

; security: only serve .php files
security.limit_extensions = .php

; logging
catch_workers_output = yes
php_admin_value[error_log] = /var/log/php/php-fpm.log
php_admin_flag[log_errors] = on

; allow PHP to read env vars from the system (needed for getenv() in config.php)
clear_env = no